[package]
edition = "2021"
name = "sold"
version = "0.73.0"

[[bin]]
name = "sold"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.79"
atty = "0.2.14"
clap = { features = ["derive"], version = "4.4.18" }
dunce = "1.0.4"
once_cell = "1.19.0"
serde = { features = ["derive"], version = "1.0.196" }
serde_json = { features = ["unbounded_depth"], version = "1.0.113" }
strip-ansi-escapes = "0.2.0"
tvm_abi = { git = "https://github.com/tvmlabs/tvm-abi", tag = "3.0.0" }
tvm_assembler = { features = ["gosh"], git = "https://github.com/tvmlabs/tvm-assembler", tag = "2.0.0" }
tvm_block = { git = "https://github.com/tvmlabs/tvm-block", tag = "2.0.0" }
tvm_types = { git = "https://github.com/tvmlabs/tvm-types", tag = "3.0.1" }

[build-dependencies]
cmake = "0.1.50"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"

[lib]
name = "sold_lib"
path = "src/lib.rs"
